[build]
  # No build command needed for static site + serverless functions
  command = ""
  # Publish directory for static files
  publish = "."
  # Functions directory for Python serverless functions
  functions = "netlify/functions"

[build.environment]
  # Force Python 3.11 (override default 3.8)
  PYTHON_VERSION = "3.11"
  # Set environment for production
  ENVIRONMENT = "production"
  # Ensure pip is available
  PIP_UPGRADE = "true"

# Python runtime configuration for Netlify Functions
[functions]
  # Explicitly set Python 3.11 runtime
  runtime = "python3.11"
  # Set timeout to 60 seconds for complex signature verification
  timeout = 60
  # Enable large payloads for PDF files
  max_age = 0
  # Include layer with additional Python packages
  included_files = ["api/**"]

# API endpoint redirects - map /api/* to Python functions
[[redirects]]
  from = "/api/verify-pades"
  to = "/.netlify/functions/verify-pades"
  status = 200
  force = true

[[redirects]]
  from = "/api/verify-cades"
  to = "/.netlify/functions/verify-cades"
  status = 200
  force = true

[[redirects]]
  from = "/api/verify-xades"
  to = "/.netlify/functions/verify-xades"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

# Serve static files (SPA fallback)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security and CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Processing settings
[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true