[build]
  command = "bash netlify-build.sh"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  PYTHON_VERSION = "3.11"
  ENVIRONMENT = "production"
  PIP_UPGRADE = "true"
  NETLIFY_SKIP_INSTALL = "true"
  NPM_FLAGS = "--no-audit --no-fund"
  YARN_FLAGS = "--ignore-scripts"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[functions]
  runtime = "python3.11"
  timeout = 60
  max_age = 0
  included_files = ["api/**"]

[[redirects]]
  from = "/api/verify-pades"
  to = "/.netlify/functions/verify-pades"
  status = 200
  force = true

[[redirects]]
  from = "/api/verify-cades"
  to = "/.netlify/functions/verify-cades"
  status = 200
  force = true

[[redirects]]
  from = "/api/verify-xades"
  to = "/.netlify/functions/verify-xades"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[build.processing]
  skip_processing = false
  
[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true