[build]
  publish = "."
  command = "echo 'No build required'"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["canvas", "puppeteer"]

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; connect-src 'self' https://*.netlify.app https://*.netlify.com;"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
